futureleadersupc/waw-backend-json:
  - source: server/db.json
    dest: db.json
  - source: server/routes.json
    dest: routes.json
  - source: .github/workflows/sync.yml
    dest: .github/workflows/sync.yml

futureleadersupc/waw-frontend-angular:
  - source: server/
    dest: server/
  - source: .github/workflows/sync.yml
    dest: .github/workflows/sync.yml
